name: 'Run lint and tests'

runs:
  using: 'composite'
  steps:
    - name: Run lint and tests
      run: fastlane run_checks
      shell: bash

    - name: Upload Test Report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4.6.2
      with:
        name: junit-test-report
        path: app/build/reports/tests/testDebugUnitTest/

    - name: Publish Test Report
      if: ${{ !cancelled() }}
      uses: dorny/test-reporter@v2.1.1
      with:
        name: JUnit Tests
        path: app/build/test-results/testDebugUnitTest/TEST-*.xml
        reporter: java-junit